name: Multi-platform compilation
on:
  push:
    branches:
      - feature/csv_output

jobs:
  build:
    name: Build on ${{ matrix.build }} version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        label: centos7
        include:
          - label: centos7
            target: linux
            container: centos:centos7
          
    steps:
      - name: Checkout Repository
        uses: action/checkout@feature/csv_output

      - name: Install packages on CentOS 7
        if: ${{ matrix.label == 'centos7' }}
        run: |
          sudo yum update -y
          sudo yum install -y
          sudo yum install gcc autoconf automake libtool make git postgresql-devel

      - name: Configure and make
        run: |
          ./configure
          make
        working-directory: alsep_tools

      - name: Install
        run: |
          sudo make install
        working-directory: alsep_tools
